### ISSUE TITLE
Crash on reading the amount of planinum coins

### ISSUE THREAD

**Issue by bloodyshade** [DatZach/CharacterEditor#6]
Here is the line in Editor.Data.cs:59
`nudCoinsPlatinum.Value = character.PlatinumCoins;`

(OBS: I do have more than 111 platinum)

Here is the dump log:

``````
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: Value of '111' is not valid for 'Value'. 'Value' should be between 'Minimum' and 'Maximum'.
Parameter name: Value
   at System.Windows.Forms.NumericUpDown.set_Value(Decimal value)
   at CharacterEditor.Forms.Editor.SyncCharacterDataToGui() in E:\cubeworld\CharacterEditor\Source\Forms\Editor.Data.cs:line 59
   at CharacterEditor.Forms.Editor.LoadCharacterDatabase() in E:\cubeworld\CharacterEditor\Source\Forms\Editor.cs:line 143
   at CharacterEditor.Forms.Editor.FormEditorShown(Object sender, EventArgs e) in E:\cubeworld\CharacterEditor\Source\Forms\Editor.cs:line 33
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Form.CallShownEvent()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()```
``````

**Comment by ghost** [comment]
Do keep in mind that this code is a work in process. However to fix that particular issue you need to adjust the amount of the updown Max value.
I'm am not sure what a normal legitimate amount of platinum coins is so I went with 1 Million. This is probably overkill.
Also note there is a lot not done, and a lot to be fixed yet.
Do this to fix the issue:
In Solution Explorer click Forms -> Then Right click Editor.cs (View Designer) Or Shift + F7.
Once in the designer view click on the "Inventory" Tab.
Click on the Platinum coins updown box one time. Then go over to properties view (Usually on the bottom right).
Find "Maximum" And adjust that number from "100" to a higher number you find suitable. I changed it to 1 million, but that is probably overdoing it. Good luck.

**Comment by bloodyshade** [comment]
I perfectly understand this is a work in progress, and I'm glad somebody is working on it, but the bug tracker exists exactly to the purpose of reporting bugs, and this is one.
In my opinion this should be set to MAX_INT, as that's the actual possible max size of the data (int32).

Thanks for the tip though.

**Comment by DatZach** [comment]
Thanks for the heads up, will be fixed in the next commit
